var state = {
    user: null,
    userPseudo: null,
    userFriendCode: null,
    dernierChangementPseudo: null,
    authLoading: true,
    authMode: 'login',
    authError: null,
    entrees: [],
    // Fil d'actualite des amis
    fil: [],
    filLoading: false,
    // Notifications (likes/commentaires recus)
    notifications: [],
    notificationsLoading: false,
    // Catalogue ami
    catalogueAmi: null,
    catalogueLoading: false,
    catalogueFiltreCategorie: 'tous',
    catalogueTri: 'date-desc',
    categorieActive: 'tous',
    vue: 'liste',
    vueSource: null,
    vueSociale: 'fil',
    modeAffichage: localStorage.getItem('journal-mode-affichage') || 'grille',
    entreeSelectionnee: null,
    entreeAmiSelectionnee: null,
    recherche: '',
    rechercheTag: '',
    rechercheTagExport: '',
    tri: 'date-desc',
    filtreNotes: [],
    filtreGenres: [],
    filtreTags: [],
    filtreTagsMode: 'ET',
    filtreStatutsLecture: [],
    filtreStatutsPossession: [],
    panneauFiltresOuvert: false,
    tagsPage: 0,
    theme: localStorage.getItem('journal-culturel-theme') || 'dark',
    formulaire: {
        titre: '',
        auteur: '',
        categorie: 'livre',
        genre: '',
        dateDecouverte: new Date().toISOString().split('T')[0],
        dateDebutLecture: '',
        note: 0,
        critique: '',
        couverture: '',
        statutLecture: 'Decouvert',
        statutPossession: [],
        dateRetour: '',
        prive: true,
        lienYoutube: '',
        typeMusique: 'album',
        lienSpotify: '',
        lienDeezer: '',
        lienQobuz: '',
        tags: [],
        ordre: 0
    },
    modeEdition: false,
    modeAjoutRapide: false,
    modeSelection: false,
    entreesSelectionnees: [],
    entreesAjouteesRapide: [],
    rechercheCouverture: false,
    rechercheOpenLibrary: false,
    resultatsOpenLibrary: [],
    dropdownOpenLibraryVisible: false,
    rechercheOMDB: false,
    resultatsOMDB: [],
    dropdownOMDBVisible: false,
    rechercheItunes: false,
    resultatsItunes: [],
    dropdownItunesVisible: false,
    rechercheYoutube: false,
    resultatsYoutube: [],
    dropdownYoutubeVisible: false,
    modalDoublons: null,
    modeImport: false,
    importResolve: null,
    importReject: null,
    syncing: false,
    toast: null,
    amis: [],
    settingsError: null,
    settingsSuccess: null,
    statsMonth: null,
    statsYear: null,
    journalStats: {},
    pileSectionActive: 'tous',
    pileExpandedSections: {},
    modalPile: null,
    dragState: {
        draggingId: null,
        draggingSection: null,
        draggingColonne: null,
        overEntreeId: null,
        overSection: null,
        overColonne: null
    }
};

document.documentElement.setAttribute('data-theme', state.theme);
